import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const home = readFileSync(new URL('../src/app/HomeClient.tsx', import.meta.url), 'utf8');
const authModal = readFileSync(new URL('../src/components/AuthModal.tsx', import.meta.url), 'utf8');
const marketStudyPreview = readFileSync(new URL('../src/components/MarketStudyPreview.tsx', import.meta.url), 'utf8');
const subscribeRoute = readFileSync(new URL('../src/app/api/stripe/subscribe/route.ts', import.meta.url), 'utf8');
const webhookRoute = readFileSync(new URL('../src/app/api/stripe/webhook/route.ts', import.meta.url), 'utf8');
const confirmRoute = readFileSync(new URL('../src/app/api/stripe/confirm/route.ts', import.meta.url), 'utf8');
const shareCreditRoute = readFileSync(new URL('../src/app/api/share-credit/route.ts', import.meta.url), 'utf8');
const rateRoute = readFileSync(new URL('../src/app/api/rate/route.ts', import.meta.url), 'utf8');
const studyRoute = readFileSync(new URL('../src/app/api/study/route.ts', import.meta.url), 'utf8');
const benchmarkRoute = readFileSync(new URL('../src/app/api/benchmark/route.ts', import.meta.url), 'utf8');
const benchmarkChart = readFileSync(new URL('../src/components/BenchmarkChart.tsx', import.meta.url), 'utf8');
const saveCurrentRoute = readFileSync(new URL('../src/app/api/history/save-current/route.ts', import.meta.url), 'utf8');
const rateSearch = readFileSync(new URL('../src/app/api/rate/search.ts', import.meta.url), 'utf8');
const strategicPlanRoute = readFileSync(new URL('../src/app/api/strategic-plan/route.ts', import.meta.url), 'utf8');
const shareCardRoute = readFileSync(new URL('../src/app/api/share-card/route.tsx', import.meta.url), 'utf8');
const historyPage = readFileSync(new URL('../src/app/history/page.tsx', import.meta.url), 'utf8');
const dashboardPage = readFileSync(new URL('../src/app/dashboard/page.tsx', import.meta.url), 'utf8');
const supabaseClient = readFileSync(new URL('../src/lib/supabase/client.ts', import.meta.url), 'utf8');
const privacyPage = readFileSync(new URL('../src/app/privacy/page.tsx', import.meta.url), 'utf8');
const termsPage = readFileSync(new URL('../src/app/terms/page.tsx', import.meta.url), 'utf8');
const studyPage = readFileSync(new URL('../src/app/study/page.tsx', import.meta.url), 'utf8');
const checkoutRoute = readFileSync(new URL('../src/app/api/checkout/route.ts', import.meta.url), 'utf8');
const extraEvalCheckoutRoute = readFileSync(new URL('../src/app/api/stripe/extra-evaluation/route.ts', import.meta.url), 'utf8');
const extraEvalConfirmRoute = readFileSync(new URL('../src/app/api/stripe/extra-evaluation/confirm/route.ts', import.meta.url), 'utf8');
const anthropicUsageLib = readFileSync(new URL('../src/lib/anthropicUsage.ts', import.meta.url), 'utf8');
const pricingLib = readFileSync(new URL('../src/lib/pricing.ts', import.meta.url), 'utf8');
const pricingRoute = readFileSync(new URL('../src/app/api/pricing/route.ts', import.meta.url), 'utf8');
const aiUsageMigration = readFileSync(new URL('../supabase/migrations/005_ai_usage_logs.sql', import.meta.url), 'utf8');

const regionalPricingDoc = readFileSync(new URL('../docs/regional-pricing-decision.md', import.meta.url), 'utf8');

assert(home.includes('Private by default') && home.includes('Privado por defecto'), 'Home should show compact privacy reassurance under the free/no-card stats in both languages.');
assert(home.includes('We don’t sell, publish, or use your ideas to build competing businesses') && home.includes('No vendemos, publicamos ni usamos tus ideas para construir negocios competidores'), 'Home privacy copy should explicitly address idea theft concerns.');
assert(home.includes('detectIdeaLanguage') && home.includes('setLang(detectedIdeaLang)'), 'Home should auto-select Spanish/English from the prompt before submitting so result language follows the idea, not just the UI.');
assert(home.includes('navigator.language') && home.includes('localStorage.getItem("lang")'), 'Home should auto-detect browser Spanish while preserving saved language preference.');
assert(rateRoute.includes('detectIdeaLanguage') && rateRoute.includes('const responseLang = lang === "es" || lang === "en" ? lang : detectIdeaLanguage(idea)'), '/api/rate should fall back to prompt-language detection when client language is missing or stale.');
assert(home.includes('showMarketStudyPreview') && home.includes('MarketStudyPreview') && home.includes('onCheckout={startMarketStudyCheckout}'), 'Market Study CTA should open a reusable explanatory preview before Stripe checkout.');
assert(marketStudyPreview.includes('Complete Market Study') && marketStudyPreview.includes('Executive Summary') && marketStudyPreview.includes('Market Analysis') && marketStudyPreview.includes('Competitor Analysis'), 'Market Study preview should mirror the real study/PDF section structure.');
assert(marketStudyPreview.includes('max-h-[82vh]') && marketStudyPreview.includes('overflow-y-auto') && marketStudyPreview.includes('blur-[3px]'), 'Market Study preview should be an internal scrollable PDF-style preview with blurred locked sections.');
assert(marketStudyPreview.includes('basada en la plantilla real del PDF') && marketStudyPreview.includes('generic preview based on the real PDF template'), 'Market Study preview should clarify it is a generic preview based on the real PDF template and the real report is generated after purchase.');
assert(marketStudyPreview.includes('🛒') && marketStudyPreview.includes('Comprar</span>') && marketStudyPreview.includes('Market Study</span>') && marketStudyPreview.includes('Secure payment processed by Stripe') && marketStudyPreview.includes('$29 USD'), 'Market Study checkout CTA should feel professional: cart icon, product-focused copy, secure payment note, and price separated as metadata.');
assert(marketStudyPreview.includes('marketStudyPrice') && marketStudyPreview.includes('Regional pricing applied when available') && marketStudyPreview.includes('Precio regional aplicado cuando está disponible'), 'Market Study preview should show the server-resolved regional price before Stripe checkout.');
assert(home.includes('marketStudyUpsellButton') && home.includes('pricing?.marketStudy.display'), 'Basic result Market Study upsell CTA should use the same server-resolved regional price as the preview and checkout.');
assert(marketStudyPreview.includes('AI Norte') && marketStudyPreview.includes('Systems over motivation'), 'Market Study preview should carry AI Norte branding, not just app UI chrome.');
assert(marketStudyPreview.includes('result.categories.map') && marketStudyPreview.includes('Basic analysis signal') && marketStudyPreview.includes('Señal del análisis básico'), 'Preview unlocked content should reuse already-generated free analysis/category cards instead of spending on new research before purchase.');
assert(!marketStudyPreview.includes('$4.8B') && !marketStudyPreview.includes('$420M'), 'Preview should not show fake market-sizing values as if generated before checkout.');
assert(studyPage.includes('AI Norte') && studyPage.includes('Systems over motivation') && studyPage.includes('Prepared as a lightweight consulting report'), 'Final Market Study should use hybrid light-consulting + AI Norte branded framing.');
assert(studyPage.includes('window.print()') && studyPage.includes('Download PDF'), 'Final Market Study should keep PDF download as the primary delivery behavior.');
assert(home.includes('Privacy') && home.includes('Terms') && home.includes('mailto:tars@ai-norte.com'), 'Footer should link to privacy, terms, and contact without adding an About section to ratemyidea.');
assert(home.includes('href="/"') && home.includes('aria-label="Go to Rate My Idea home"'), 'Header Rate My Idea logo should link back to the home/start state.');
assert(privacyPage.includes('We do not sell your ideas') && privacyPage.includes('No vendemos tus ideas'), 'Privacy page should include the agreed idea-protection promise in EN and ES.');
assert(termsPage.includes('not financial, legal, investment, or professional advice') && termsPage.includes('No garantiza rentabilidad'), 'Terms page should include compact liability/disclaimer language.');
assert(authModal.includes('resetPasswordForEmail') && authModal.includes('Password reset email sent') && authModal.includes('Te enviamos un correo para restablecer tu contraseña'), 'Auth modal should include password reset flow with localized success copy.');
assert(authModal.includes('Invalid login credentials') && authModal.includes('Reset password'), 'Auth modal should surface a visible reset-password action after invalid credentials.');
assert(home.includes('saveCurrentResultToProHistory') && home.includes('/api/history/save-current'), 'Logging into Pro with an open anonymous analysis should save that current result into Pro history.');
assert(saveCurrentRoute.includes('Pro subscription required') && saveCurrentRoute.includes('user_subscriptions') && saveCurrentRoute.includes('idea_text'), 'Save-current history API should only attach an open result to an authenticated Pro user.');
assert(supabaseClient.includes('isValidSupabaseUrl') && supabaseClient.includes('try {') && supabaseClient.includes('return false'), 'Supabase browser client should ignore invalid placeholder URLs instead of crashing local runtime.');

assert(authModal.includes('emailRedirectTo'), 'Supabase signup should set emailRedirectTo so production confirmations do not go to localhost.');
assert(authModal.includes('window.location.origin'), 'Supabase signup redirect should use the current deployed origin.');

assert(!authModal.includes('window.location.href = "/upgrade"'), 'Daily-limit Upgrade to Pro CTA must not route to missing /upgrade page.');
assert(authModal.includes('onUpgrade'), 'AuthModal should expose an onUpgrade callback so the modal can start Pro checkout.');
assert(home.includes('userId: userSession?.userId'), 'Pro checkout request should include authenticated userId.');
assert(subscribeRoute.includes('const metadata = { userId') && subscribeRoute.includes('metadata,'), 'Stripe subscription checkout should persist userId in checkout metadata.');
assert(subscribeRoute.includes('subscription_data: { metadata }'), 'Stripe subscription checkout should also persist userId in subscription_data.metadata.');
assert(subscribeRoute.includes('session_id={CHECKOUT_SESSION_ID}'), 'Stripe success_url should include Checkout Session ID so the client can confirm Pro on return.');
assert(confirmRoute.includes('stripe.checkout.sessions.retrieve') && confirmRoute.includes('user_subscriptions') && confirmRoute.includes('upsert'), 'Stripe confirm route should retrieve the checkout session and upsert Pro entitlement after return from Stripe.');
assert(home.includes('fetch("/api/stripe/confirm"'), 'Home should confirm Stripe checkout on subscribed=true return before relying only on webhooks.');
assert(webhookRoute.includes('sub.metadata?.userId'), 'Stripe webhook should prefer subscription metadata userId for Pro unlock.');
assert(webhookRoute.includes('checkout.session.completed'), 'Stripe webhook should also unlock Pro from checkout.session.completed as a fallback before subscription metadata arrives.');

assert(!home.includes('if (data.category) fetchBenchmark(data.overall, data.category);'), 'Free evaluations must not fetch benchmark data automatically.');
assert(home.includes('if ((userSession?.isPro || data.isPro) && data.category) fetchBenchmark(data.overall, data.category, data.categories);'), 'Benchmark fetch should be gated to current Pro users only and pass user subscores.');
assert(home.includes('{isCurrentPro && benchmark && ('), 'Benchmark component should render only for Pro users.');

assert(authModal.includes('isAuthenticated?: boolean'), 'AuthModal should know when user is already signed in.');
assert(authModal.includes('isLimitSignedIn = isLimit && isAuthenticated'), 'Daily-limit modal should have a signed-in variant instead of asking logged-in users to sign in.');
assert(authModal.includes('!isAuthenticated && ('), 'Daily-limit modal should hide auth form when user is already signed in.');

assert(!shareCardRoute.includes('backgroundImage:'), 'Share card should not use @vercel/og-fragile CSS backgroundImage gradients.');
assert(shareCardRoute.includes('rgba(108, 58, 255, 0.06)'), 'Share card should use supported rgba color syntax with spaces for OG rendering.');

assert(home.includes('interface EvaluationMeta'), 'Home UI should track evaluation-count metadata returned by /api/rate.');
assert(home.includes('freeEvaluationsUsed'), 'Result flow should know whether this is the 1st or 2nd free evaluation.');
assert(home.includes('canClaimShareCredit'), 'Share CTA should show +1 free evaluation only when the user can claim it.');
assert(home.includes('claimShareCreditAfterAuth'), 'Anonymous share-credit claims should route through auth before granting persistent credit.');
assert(home.includes('startExtraEvaluationCheckout()'), 'After the free evaluation, the secondary CTA should start paid extra-evaluation checkout instead of making Pro the only path.');
assert(home.includes('Buy another') && home.includes('$1 USD'), 'English final free-evaluation CTA copy should stay compact while preserving the paid price signal.');
assert(home.includes('Comprar otra') && home.includes('$1 USD'), 'Spanish final free-evaluation CTA copy should stay compact while preserving the paid price signal.');
assert(home.includes('+1 free evaluation') && home.includes('+1 evaluación gratis') && home.includes('role="tooltip"') && home.includes('group-hover:opacity-100'), 'Share CTA should move the +1 evaluation incentive into a hover/focus tooltip instead of crowding the button label.');
assert(home.includes('handlePostShareCreditClaim'), 'Share image should automatically route eligible users into +1 claim after sharing.');
assert(home.includes('PENDING_SHARE_CREDIT_KEY'), 'Share-credit claim intent should persist through email confirmation redirects.');
assert(home.includes('localStorage.setItem(PENDING_SHARE_CREDIT_KEY'), 'Anonymous share-credit claim should be stored before opening signup.');
assert(home.includes('claimPendingShareCredit'), 'Home boot should claim pending share credit after Supabase restores the confirmed email session.');
assert(home.includes('localStorage.removeItem(PENDING_SHARE_CREDIT_KEY'), 'Pending share-credit intent should clear after successful claim/signout.');
assert(!home.includes('Claim +1 free evaluation'), 'Share modal should not render a separate repetitive Claim +1 free evaluation button.');
assert(shareCreditRoute.includes('granted: true') && shareCreditRoute.includes('granted: false'), 'Share-credit API should tell the UI whether a new credit was actually granted.');

assert(rateRoute.includes('const FREE_LIMIT = 1'), '/api/rate should allow exactly one free basic evaluation before share or paid extra-eval paths.');
assert(home.includes('startExtraEvaluationCheckout') && home.includes('Buy another') && home.includes('Comprar otra'), 'Daily-limit result actions should offer a simple paid extra evaluation instead of making Pro the only next step.');
assert(home.includes('extraEvalCheckoutLoading') && home.includes('params.get("extra_eval") === "success"'), 'Home should track paid extra-evaluation checkout separately and confirm it on Stripe return.');
assert(extraEvalCheckoutRoute.includes('STRIPE_EXTRA_EVAL_PRICE_ID') && extraEvalCheckoutRoute.includes('mode: "payment"') && extraEvalCheckoutRoute.includes('purchaseType: "extra_evaluation"'), 'Extra evaluation checkout route should create a one-time Stripe payment with explicit metadata.');
assert(extraEvalConfirmRoute.includes('stripe.checkout.sessions.retrieve') && extraEvalConfirmRoute.includes('increment_extra_credit') && extraEvalConfirmRoute.includes('purchaseType') && extraEvalConfirmRoute.includes('extra_evaluation'), 'Extra evaluation confirm route should verify Stripe checkout and increment user extra_credits through the idempotent credit RPC.');
assert(webhookRoute.includes('purchaseType === "extra_evaluation"') && webhookRoute.includes('increment_extra_credit'), 'Stripe webhook should also grant paid extra evaluation credits as a fallback.');
assert(home.includes('const [market, setMarket]') && home.includes('Market / location') && home.includes('Mercado / ubicación'), 'Home form should include one optional market/location field without turning the app into a long form.');
assert(rateRoute.includes('marketContext') && rateRoute.includes('detectMarketContext') && rateRoute.includes('If no market/location is specified'), '/api/rate should explicitly handle market/location assumptions in the prompt.');
assert(rateRoute.includes('buildSearchQueries') && rateRoute.includes('marketContext.searchMarket'), '/api/rate should use deterministic query planning with detected/provided market context.');
assert(rateSearch.includes('provider?:') && rateSearch.includes('query?:') && rateSearch.includes('usedInPrompt?:') && rateSearch.includes('provider: "serper"'), 'Search results should preserve source provider/query/usedInPrompt metadata.');
assert(rateSearch.includes('sourceQuality: r.sourceQuality') && rateSearch.includes('qualityTier: r.qualityTier') && rateSearch.includes('query: r.query') && rateSearch.includes('provider: r.provider'), 'Client sources should retain source quality, tier, provider, and query for observability.');
assert(marketStudyPreview.includes('deeper research') && marketStudyPreview.includes('investigación más profunda'), 'Market Study preview should explain the deeper research in simple product language.');

assert(rateRoute.includes('sub?.status === "active" || sub?.status === "trialing"'), '/api/rate should treat active and trialing Pro subscriptions consistently with the client and Stripe confirm flow.');
assert(!rateRoute.includes('countColumn = userId ? "user_id" : "ip_hash"'), '/api/rate must not reset free limits by switching from anonymous IP counting to authenticated user_id-only counting after signup.');
assert(rateRoute.includes('user_id.eq.${userId},ip_hash.eq.${ipHash}') && rateRoute.includes('usageRows?.length'), '/api/rate should combine same-day authenticated user_id usage with same-IP anonymous usage so signup does not grant a second free quota.');
assert(rateRoute.includes('consume_extra_credit'), '/api/rate should consume extra share credits through the atomic Supabase RPC before allowing an over-limit evaluation.');
assert(rateRoute.includes('extraCreditConsumed'), '/api/rate should track whether the current evaluation used an extra credit for accurate response metadata.');
assert(rateRoute.includes('Promise.race') && rateRoute.includes('ANTHROPIC_TIMEOUT_MS'), '/api/rate should bound Anthropic calls with a timeout to control cost and stuck requests.');
assert(rateSearch.includes('AbortController') && rateSearch.includes('SERPER_TIMEOUT_MS'), 'Serper search should have a request timeout so research failures do not hang evaluations.');
assert(rateSearch.includes('filterSourcesForQuality') && rateSearch.includes('SOURCE_SPAM_DOMAINS') && rateSearch.includes('SOURCE_FALLBACK_LIMIT'), 'Search module should expose source-quality filtering with spam exclusions and a bounded fallback.');
assert(rateSearch.includes('qualityTier') && rateSearch.includes('sourceQuality'), 'Search results should carry source quality metadata for LLM grounding and client transparency.');
assert(rateSearch.includes('sort((a, b) => b.sourceQuality - a.sourceQuality'), 'Source filtering should rank stronger domains/snippets before weak sources.');
assert(rateRoute.includes('const qualityResults = markSourcesUsedInPrompt(filterSourcesForQuality(uniqueResults))') && rateRoute.includes('formatSearchContext(qualityResults)'), '/api/rate should feed only quality-filtered sources into the LLM research context and mark what was used.');
assert(rateRoute.includes('formatSourcesForClient(qualityResults)'), '/api/rate should expose the same quality-filtered source set to users.');
assert(rateRoute.includes('qualityResults.length === 0') && rateRoute.includes('source_quality_empty'), '/api/rate should log when source filtering removes all research results instead of silently grounding on weak sources.');
assert(rateRoute.indexOf('filterSourcesForQuality') < rateRoute.indexOf('formatSearchContext'), 'Source filtering must run before building the Claude research context.');
assert(rateRoute.indexOf('filterSourcesForQuality') < rateRoute.indexOf('fetchAnthropicWithTimeout'), 'Source filtering must happen before spending on the Claude call.');
assert(rateRoute.includes('FREE_DAILY_GLOBAL_LIMIT') && rateRoute.includes('{ count: "exact", head: true }') && rateRoute.includes('cost_guardrail'), '/api/rate should have an env-based global free daily cap before spending on search/LLM calls.');
assert(rateRoute.includes('isSuspiciousIdea') && rateRoute.includes('abuse_check_failed'), '/api/rate should reject obvious bot/spam idea payloads before spending on search/LLM calls.');
assert(rateRoute.includes('TURNSTILE_SECRET_KEY') && rateRoute.includes('challenges.cloudflare.com/turnstile/v0/siteverify') && rateRoute.includes('turnstile_required'), '/api/rate should support conditional Cloudflare Turnstile verification for suspicious/over-threshold anonymous users.');
assert(home.includes('NEXT_PUBLIC_TURNSTILE_SITE_KEY') && home.includes('turnstileToken') && home.includes('https://challenges.cloudflare.com/turnstile/v0/api.js'), 'Home should render and submit a Cloudflare Turnstile token when bot protection is configured.');
assert(rateRoute.indexOf('isSuspiciousIdea') < rateRoute.indexOf('const searchQueries'), 'Abuse checks must run before web research starts.');
assert(rateRoute.includes('const { data: savedEvaluation, error: saveError } = await supabase') && rateRoute.includes('.select("id")') && !rateRoute.includes('.then(({ error })'), '/api/rate must await evaluation persistence and return the saved evaluation id before responding.');
assert(anthropicUsageLib.includes('estimateAnthropicCostUsd') && anthropicUsageLib.includes('input_tokens') && anthropicUsageLib.includes('output_tokens'), 'Anthropic usage helper should estimate USD cost from provider token usage.');
assert(aiUsageMigration.includes('create table if not exists ai_usage_logs') && aiUsageMigration.includes('estimated_cost_usd') && aiUsageMigration.includes('endpoint text not null'), 'Supabase migration should create ai_usage_logs for endpoint/model/token/cost observability.');
assert(rateRoute.includes('logAnthropicUsage') && rateRoute.includes('endpoint: "/api/rate"') && rateRoute.includes('evaluationId:'), '/api/rate should log Anthropic usage with the saved evaluation id.');
assert(studyRoute.includes('logAnthropicUsage') && studyRoute.includes('endpoint: "/api/study"'), '/api/study should log Anthropic usage for paid market studies.');
assert(strategicPlanRoute.includes('logAnthropicUsage') && strategicPlanRoute.includes('endpoint: "/api/strategic-plan"'), '/api/strategic-plan should log Anthropic usage for Pro next-step generation.');

const signOutMatch = home.match(/(?:async )?function handleSignOut\(\) \{([\s\S]*?)\n  \}/);
assert(signOutMatch, 'Home should define handleSignOut.');
const signOutBody = signOutMatch?.[1] ?? '';
assert(signOutBody.includes('await supabase?.auth.signOut()'), 'Sign out should clear the real Supabase session so reload does not auto-sign back in.');
assert(signOutBody.includes('setUserProfile(null)') && signOutBody.includes('setEvaluationMeta(null)'), 'Sign out should clear profile and evaluation metadata so Pro entitlement cannot linger in UI state.');
assert(signOutBody.includes('setBenchmark(null)') && signOutBody.includes('setStrategicPlan(null)') && signOutBody.includes('setIdeaHistory([])'), 'Sign out should clear Pro-only benchmark, action plan, and history state immediately.');
assert(signOutBody.includes('setResult(null)') && signOutBody.includes('setSelectedHistoryId(null)'), 'Sign out should clear selected Pro evaluation/result so historical Pro data is not visible after logout.');

assert(authModal.includes('Create a free account to claim your extra evaluation'), 'Auth modal should explain login/signup is required to claim +1 free evaluation.');
assert(authModal.includes('Crea una cuenta gratis para reclamar tu evaluación extra'), 'Auth modal should explain the +1 claim in Spanish.');

assert(home.includes('proCheckoutLoading') && home.includes('marketStudyCheckoutLoading'), 'Pro and Market Study checkout loading states should be isolated.');
assert(home.includes('window.addEventListener("pageshow"'), 'Checkout loading states should reset when returning from Stripe/cancel/back navigation.');
assert(!home.includes('disabled={checkoutLoading}'), 'A shared checkoutLoading flag should not disable unrelated result actions.');
assert(home.includes('const isCurrentPro'), 'Result UI should use a single current Pro state instead of stale userSession checks.');
assert(home.includes('isCurrentPro && benchmark'), 'Benchmark should render from the current Pro state.');
assert(home.includes('isCurrentPro && (') && home.includes('Pro member'), 'Pro users should see a visible Pro member indicator beyond the small nav badge.');
assert(home.includes('showHeaderUpgradeCta'), 'Header should explicitly decide when to show the Pro upgrade CTA.');
assert(home.includes('Get Pro account'), 'Header should show Get Pro account CTA for anonymous/free users.');
assert(home.includes('Obtener cuenta Pro'), 'Header should localize the Pro account CTA for Spanish users.');
assert(home.includes('✨ Pro member'), 'Header Pro status should remain visible for Pro users.');
assert(home.includes('const isProfileHydrating'), 'Header should avoid showing Get Pro account while an authenticated profile is still hydrating.');
assert(home.includes('subscription?.status === "active" || subscription?.status === "trialing"'), 'Client Pro entitlement should accept trialing Stripe subscriptions just like the Dashboard gate.');
assert(home.includes('text-amber-100') && home.includes('{userSession.email.split("@")[0]}'), 'Header Pro status should be plain bold text followed by the username, not another pill button.');
assert(!home.includes('inline-flex items-center rounded-full border border-amber-300/40 bg-gradient-to-r from-amber-300/25 to-yellow-500/15 px-3 py-1 text-xs font-bold text-amber-100 shadow-lg shadow-amber-300/20'), 'Header Pro member status should not use a bordered/gold pill that resembles a button.');
assert(home.includes('pro-result-panel'), 'Pro evaluations should render a premium result panel near the top, not feel like free results with extras appended.');
assert(home.includes('Pro analysis unlocked'), 'Pro result panel should clearly announce the upgraded analysis experience.');
assert(home.includes('Benchmark included') && home.includes('10-step plan ready'), 'Pro result panel should summarize benchmark and next-step plan benefits.');
assert(home.includes('Pro insight benchmark'), 'Benchmark should be framed as a Pro insight section.');
assert(home.includes('function getProUpsellCopy'), 'Free result Pro upsell should use score-aware contextual copy instead of static SaaS bullets.');
assert(home.includes('Make this idea stronger with Pro') && home.includes('Mejorar esta idea con Pro'), 'Free result Pro upsell should frame Pro as improving the current idea.');
assert(home.includes('This idea scored high. Pro helps you protect the upside') && home.includes('Esta idea salió fuerte. Pro te ayuda a proteger lo bueno'), 'Pro upsell should adapt copy for high-scoring ideas in both languages.');
assert(home.includes('This idea has potential, but the weak spots matter') && home.includes('Esta idea tiene potencial, pero los puntos débiles importan'), 'Pro upsell should adapt copy for mid-scoring ideas in both languages.');
assert(home.includes('This idea may need a pivot') && home.includes('Esta idea quizá necesita un giro'), 'Pro upsell should adapt copy for low-scoring ideas in both languages.');
assert(home.includes('Compare your idea') && home.includes('Compara tu idea') && home.includes('Stress-test the weak spots') && home.includes('Presiona los puntos débiles'), 'Pro upsell should render icon cards for comparison and weak-spot work.');
assert(home.includes('locked-pro-benchmark-preview') && home.includes('Unlock Pro analysis') && home.includes('Mejorar con Pro'), 'Pro benchmark preview should be separated from the Pro upsell while keeping the stronger CTA copy.');
assert(home.includes('$9/mo') && home.includes('$9 USD/mes'), 'Pro upsell should show the monthly Pro price in English and Spanish before checkout.');
assert(home.includes('space-y-5') && home.includes('lg:grid-cols-4') && home.includes('lg:flex-row'), 'Pro upsell should be a row-by-row layout: headline row, four-card row, then horizontal benchmark/CTA row.');
assert(!home.includes('xl:grid-cols-[minmax(0,1fr)_minmax(20rem,0.95fr)]'), 'Pro upsell should no longer split the copy/cards and benchmark into side-by-side columns.');
assert(!home.includes('lg:grid-cols-[minmax(0,1fr)_22rem]'), 'Pro upsell should not use the old fixed-width desktop split that caused poor distribution in smoke testing.');
assert(home.includes('hover:shadow-[0_0_32px_rgba(108,58,255,0.45)]') && home.includes('hover:-translate-y-0.5'), 'Pro CTA should be larger and glow/lift on hover.');
assert(home.includes('hover:shadow-[0_0_32px_rgba(108,58,255,0.45)]') && marketStudyPreview.includes('hover:shadow-[0_0_32px_rgba(108,58,255,0.45)]'), 'Market Study checkout CTA should share the hover glow treatment.');
assert(!home.includes('✓ {lang === "es" ? "Evaluaciones ilimitadas"') && !home.includes('Benchmark vs otras ideas'), 'Free result Pro upsell should not use the old generic feature checklist.');
assert(home.includes('Buy another') && home.includes('Comprar otra') && home.includes('rounded-full bg-white/15') && !home.includes('Buy one more evaluation · $1.00 USD') && !home.includes('Comprar otra evaluación · $1.00 USD'), 'Paid extra-evaluation CTA should be a compact action plus small price badge, not a long sentence inside the button.');
assert(home.includes('CHECKOUT_RESULT_KEY') && home.includes('persistCurrentResultForCheckout') && home.includes('restoreCurrentResultFromCheckout'), 'Checkout redirects should preserve the open analysis so cancel/back from Stripe does not reset the page.');
assert(home.includes('setEvaluationMeta(saved.evaluationMeta || null);\n      sessionStorage.removeItem(CHECKOUT_RESULT_KEY);'), 'Checkout result restoration should be one-shot so refresh/logo reset can return to the new-idea form instead of reviving stale analyses forever.');
assert(marketStudyPreview.includes('Market Study adds deeper research') && marketStudyPreview.includes('El Market Study agrega investigación más profunda'), 'Market Study preview should include a small outside-the-PDF explainer/diagram contrasting basic analysis with deeper research.');
assert(marketStudyPreview.includes('Volver al análisis básico') && marketStudyPreview.includes('Back to basic analysis'), 'Market Study preview should include a clear in-page/back-to-basic button instead of relying on browser back.');
assert(marketStudyPreview.includes('sm:text-left') && marketStudyPreview.includes('text-center'), 'Market Study preview header should center title/subtext on mobile and relax to left alignment on larger screens.');
assert(marketStudyPreview.includes('kicker={isEs ? "desbloqueado" : "unlocked"}'), 'Market Study unlocked-section kicker should be short: DESBLOQUEADO / UNLOCKED, not a long caveat.');
assert(marketStudyPreview.includes('text-2xl">🛒') && marketStudyPreview.includes('Comprar</span>') && marketStudyPreview.includes('Market Study</span>'), 'Market Study mobile checkout CTA should use a larger cart icon and split Comprar / Market Study into two lines.');
assert(marketStudyPreview.includes('Probabilidad: media') && marketStudyPreview.includes('Likelihood: medium') && marketStudyPreview.includes('Impacto: alto') && marketStudyPreview.includes('Impact: high'), 'Risk/verdict badges should spell out likelihood and impact instead of cryptic L:/I: labels.');
assert(home.includes('shareCreditBadgeAboveCta') && home.includes('Enviar') && home.includes('Send') && !home.includes('Compartir imagen'), 'Share modal should simplify the primary share CTA around the send action, with +1 incentive outside the button.');
assert(home.includes('proBenchmarkPreviewHero') && home.includes('bg-gradient-to-b') && home.includes('Comparación visible antes del blur') && home.includes('Visible comparison before blur'), 'Locked Pro benchmark preview should show a larger, understandable visual surface before the blur/fade in both languages.');
assert(rateRoute.includes('basicBenchmark') && rateRoute.includes('Based on the current sample of evaluated ideas'), '/api/rate should attach a lightweight directional benchmark to every basic evaluation.');
assert(home.includes('result.basicBenchmark') && home.includes('Category signal') && home.includes('Señal de categoría'), 'Free results should render a basic benchmark card inside the main analysis.');
assert(home.includes('categoryAverage') && home.includes('Your score') && home.includes('Category average'), 'Free benchmark should include a visual your-score vs category-average comparison.');
assert(home.includes('This benchmark is directional, not a scientific ranking') && home.includes('muestra actual de ideas evaluadas'), 'Benchmark UI should avoid overpromising and include directional/sample disclaimer copy.');
assert(rateRoute.includes('benchmarkSignals') && rateRoute.includes('normalizeBenchmarkSignals') && rateRoute.includes('countBenchmarkTags'), '/api/rate should request, normalize, persist, and aggregate benchmarkSignals without a second AI call.');
assert(rateRoute.includes('max_tokens: 2600'), '/api/rate should leave enough output budget for Spanish researched evaluations with benchmarkSignals; lower caps can truncate valid JSON and cause Analysis format errors.');
assert(rateRoute.includes('? "normalized_tags"') && rateRoute.includes(': "category_fallback"') && rateRoute.includes('fallbackPattern.commonWeakness'), 'Basic benchmark should prefer normalized tag counts and fall back to category heuristics when sample size is low.');
assert(home.includes('signalSource') && home.includes('Pattern confidence') && home.includes('Confianza de patrón'), 'Free benchmark UI should disclose whether common signals are tag-based or heuristic fallback.');
assert(home.includes('score-share-card') && !home.includes('inline-share-card-preview'), 'Basic results should integrate share-card actions into the main score section instead of adding a separate share-card section.');
assert(home.includes('scoreHideIdeaToggle') && home.includes('peer-checked:translate-x-5') && home.includes('rounded-full peer-checked:bg-[var(--electric)]'), 'Score card should use a real rounded on/off toggle for showing/hiding the idea.');
assert(home.includes('onClick={() => setShowShareModal(true)}') && home.includes('aria-label={lang === "es" ? "Abrir preview para compartir score card" : "Open score card share preview"}'), 'Score card should have one compact share button that opens the preview/share modal.');
assert(!home.includes('Download score card image') && !home.includes('Copy link and text') && !home.includes('⬇️ {lang === "es" ? "Descargar"') && !home.includes('🔗 {lang === "es" ? "Copiar"'), 'Score card should remove separate download/copy actions from the first result section.');
assert(home.includes('Ocultar idea') && home.includes('Hide idea') && home.includes('🔒') && !home.includes('Comparte una versión limpia'), 'Score share card should use an intentional lock-style hide-idea toggle and avoid explanatory copy bloat.');
assert(!home.includes('Comparte tu score') && !home.includes('Share your score'), 'Score card should remove the redundant share heading so the score and idea name carry the hierarchy.');
assert(home.includes('h-44 w-44 sm:h-48 sm:w-48') && home.includes('text-5xl font-bold sm:text-6xl'), 'Score ring should be visually larger so the score is the hero of the first result section.');
assert(home.includes('scorePrimaryShareButton') && home.includes('w-fit') && home.includes('px-4 py-2.5 text-sm'), 'Score card share button should stay compact relative to its text, not span a whole row.');
assert(home.includes('locked-pro-benchmark-preview') && home.includes('blurredProBenchmarkSurface') && home.includes('Top 18%') && home.includes('h-24') && home.includes('relative overflow-hidden'), 'Locked Pro benchmark preview should simulate a full blurred Pro benchmark section with bar chart and percentile badge.');
assert(!home.includes('min-w-0 flex-1 space-y-2 rounded-2xl border border-white/10 bg-black/20 p-4 blur-[1px]'), 'Locked Pro benchmark preview should not show a small blurred image/card inside the section.');
assert(regionalPricingDoc.includes('visible, transparent pricing experiment') && regionalPricingDoc.includes('$29 USD') && regionalPricingDoc.includes('LATAM') && regionalPricingDoc.includes('Stripe env vars'), 'Regional pricing should be documented as a transparent Market Study experiment with Stripe Price ID/env guardrails.');
assert(pricingLib.includes('resolvePricing') && pricingLib.includes('x-vercel-ip-country') && pricingLib.includes('MARKET_STUDY_PRICE_LATAM_ID'), 'Regional pricing should resolve server-side from country headers and Stripe Price IDs, not client-side IP logic.');
assert(pricingRoute.includes('resolvePricing') && pricingRoute.includes('NextResponse.json'), '/api/pricing should expose display-only pricing resolved by the same server pricing helper.');
assert(checkoutRoute.includes('resolvePricing') && checkoutRoute.includes('pricing.marketStudy.priceId') && checkoutRoute.includes('pricingRegion') && checkoutRoute.includes('detectedCountry'), 'Market Study checkout should use the same server-side regional pricing resolver and record pricing metadata.');
assert(home.includes('fetch("/api/pricing"') && home.includes('setPricing') && home.includes('pricing={pricing}'), 'Home should load regional pricing from /api/pricing and pass it into the Market Study preview.');
assert(benchmarkRoute.includes('subscoreAverages') && benchmarkRoute.includes('improvementLevers') && benchmarkRoute.includes('strongerThanSimilar') && benchmarkRoute.includes('weakerThanSimilar'), 'Pro benchmark API should return richer comparison fields beyond percentile and histogram.');
assert(benchmarkChart.includes('Percentile badge') && benchmarkChart.includes('sub-score comparison') && benchmarkChart.includes('improvement levers'), 'Pro benchmark component should render percentile, sub-score comparison, and improvement levers.');
assert(home.includes('Build the 10-step action plan'), 'Generate 10 steps CTA should be more protagonist for Pro users.');
assert(home.includes('text-center') && home.includes('Benchmark included') && home.includes('10-step plan ready'), 'Pro result summary cards should center their text.');
assert(home.includes('formatStrategicPlanSteps'), 'Generated 10-step plans should be parsed into structured cards instead of rendered as plain text.');
assert(home.includes('cleanStepMarkdown'), 'Generated 10-step plan rendering should strip markdown artifacts like **Title:** before display.');
assert(home.includes('Step ${step.number}') || home.includes('Paso ${step.number}'), 'Generated 10-step cards should label each step clearly.');
assert(home.includes('10-step action plan') && home.includes('Pro only'), 'Completed 10 Next Steps section should repeat the Pro only badge treatment.');
assert(strategicPlanRoute.includes('Do not use Markdown bold markers') && strategicPlanRoute.includes('No uses marcadores Markdown de negritas'), 'Next-step prompt should prevent broken bold marker output like **Title:**.');
assert(!home.includes('{/* Pro member status */}'), 'Old appended Pro member status block should be removed or redesigned.');
assert(!home.includes('Unlimited evaluations, benchmark, and history are active.'), 'Pro result copy should not feel like a passive status message appended to a free result.');
assert(!home.includes('Generate 10 concrete next steps for this idea'), 'Old passive Pro next-step CTA copy should be replaced with a stronger action block.');
assert(!home.includes('href={`/history?token=${encodeURIComponent(userSession.token)}`}'), 'Header should not show a standalone History link; Pro history belongs inside the dashboard.');
assert(!home.includes('<a href="/history"'), 'History link without token is broken and should not render.');
assert(!home.includes('handleClaimShareCredit'), 'Claiming +1 free evaluation should not be a separate share-modal action.');
assert(!home.includes('if (canClaimShareCredit && !userSession) {\n      setClaimShareCreditAfterAuth'), 'Share image should not be blocked by the auth claim modal.');
assert(home.includes('handleShareWithImage') && home.includes('handleDownloadImage'), 'Share image should have a download fallback when native file sharing is unavailable.');

assert(historyPage.includes('user_subscriptions') && historyPage.includes('subscription?.plan !== "pro"'), 'History page should be gated to Pro subscribers server-side.');
assert(home.includes('interface HistoryEvaluation'), 'Home should own the Pro history navigator instead of depending on a separate dashboard route.');
assert(home.includes('fetchIdeaHistory') && home.includes('result_json'), 'Home should fetch saved Pro evaluations with full result_json for in-page history.');
assert(home.includes('selectHistoryEvaluation'), 'Pro users should be able to restore a saved evaluation from the in-page history navigator.');
assert(home.includes('id="pro-history"') && home.includes('Pro history'), 'Home should render a Pro history section after sign-in, before a new evaluation is required.');
assert(home.includes('lg:sticky') && home.includes('lg:top-24'), 'Pro history should become a sticky desktop sidebar instead of stacking into the result flow.');
assert(home.includes('scroll-mt-28') && home.includes('href="#pro-history"'), 'Pro history anchors should account for the fixed header scroll offset.');
assert(home.includes('lg:grid-cols-[minmax(0,1fr)_20rem]'), 'Pro Home layout should reserve a desktop sidebar column for history.');
assert(home.includes('onSuccess={handleAuthSuccess}') && home.includes('await refreshUserAndProfile()'), 'Signing in from a cookie-less Pro account should hydrate Pro status immediately.');
assert(home.includes('cursor-pointer') && home.includes('Get Pro account'), 'Header Get Pro account CTA should show a pointer cursor on hover.');
assert(home.includes('getErrorMessage'), 'Home should normalize API/client errors before rendering them to users.');
assert(home.includes('Something went wrong. Try again.') && !home.includes('throw new Error(errData.error || "Something went wrong. Try again.")'), 'Home should not throw raw API error objects that render as [object Object].');
assert(!home.includes('Open dashboard'), 'Broken Open dashboard header CTA should be removed while history lives in the main evaluation view.');
assert(!home.includes('Review this in Dashboard'), 'Pro result should not link to the unstable Dashboard route.');
assert(strategicPlanRoute.includes('NEXT_STEPS_MODEL') && strategicPlanRoute.includes('max_tokens: 1000'), 'Next-step generation should use a configurable model and lower token cap than the old 30-day plan.');
assert(strategicPlanRoute.includes('exactly 10 concrete next steps') && strategicPlanRoute.includes('exactamente 10 siguientes pasos'), 'Strategic plan endpoint should now generate 10 next steps, not a 30-day plan.');

console.log('smoke checks passed');
